version: "3.9"
name: mataocred_landingpage
services:
  mataocred_landingpage_web:
    container_name: mataocred_landingpage_web
    image: vitor2128/mataocred-landingpage-web:1.0.2
    restart: unless-stopped
    networks:
      - mataocred_landingpage_network

  mataocred_landingpage_proxy_web:
    container_name: mataocred_landingpage_proxy_web
    image: vitor2128/mataocred-landingpage-proxy-web:1.0.5
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - mataocred_landingpage_web
    networks:
      - mataocred_landingpage_network

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   networks:
  #     - mataocred_landingpage_network
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email mataocred@gmail.com -d mataocred.com.br --agree-tos

networks:
  mataocred_landingpage_network:
    driver: bridge
