version: "3.9"
name: mataocred_landingpage
services:
  mataocred_landingpage_web:
    container_name: mataocred_landingpage_web
    image: vitor2128/mataocred-landingpage-web:1.0.1
    networks:
      - mataocred_landingpage_network

  mataocred_landingpage_proxy_web:
    container_name: mataocred_landingpage_proxy_web
    restart: unless-stopped
    image: nginx:1.25.2-alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mataocred_landingpage_web
    networks:
      - mataocred_landingpage_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email mataocred@gmail.com -d mataocred.com.br --agree-tos

networks:
  mataocred_landingpage_network:
    driver: bridge
